config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :rooms
    resources :users
  end

  resources :rooms do
    resources :reviews, only: [:create, :update], module: :rooms
  end
  
  get '/:locale' => 'home#index', locale: /en|pt/
  resource :confirmation, only: [:show]
  resource :user_sessions, only: [:create, :new, :destroy]
  root 'home#index'

end

app/models/CreateUsers.rb
class CreateUsers < ActiveRecord::Migration
	def change
		create_table :users do |t|
			t.string :full_name
			t.string :email
			t.string :password
			t.string :location
			t.text :bio

			t.index :email, unique: true

			t.timestamps
		end
		
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
  # Criamos um Array de 5 elementos, ao invés de range
  POINTS = (1..5).to_a

  belongs_to :user
  belongs_to :room, counter_cache: true

  validates_uniqueness_of :user_id, scope: :room_id
  validates_presence_of :points, :user_id, :room_id
  validates_inclusion_of :points, in: POINTS

  def self.stars
    (average(:points) || 0).round
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :reviews, dependent: :destroy
	has_many :reviewed_rooms, through: :reviews, source: :room
	belongs_to :user

	def complete_name
		"#{title}, #{location}"
	end

	def self.most_recent
		all.order(:created_at).limit(3)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :reviews, dependent: :destroy
	has_many :rooms, dependent: :destroy

	scope :confirmed, -> { where.not(confirmado_em: nil)}

	validates_presence_of :email, :full_name, :location
	validates_length_of :bio, minumum: 30, allow_blank: false
	validates_format_of :email, with: EMAIL_REGEXP

	has_secure_password

	before_create do |user|
		user.codigo_confirmacao = SecureRandom.urlsafe_base64
	end

	def self.authenticate(email, password)
		confirmed.find_by(email: email).try(:authenticate, password)
	end

	def confirm!
		return if confirmed?

		self.confirmado_em = Time.current 
		self.codigo_confirmacao = ''
		save!
	end

	def confirmed?
		confirmado_em.present?
	end
end

app/models/user_session.rb
class UserSession 
	include ActiveModel::Model

	attr_accessor :email, :password
	validates_presence_of :email, :password

	def initialize(session, attributes = {})
		@session = session
		@email = attributes[:email]
		@password = attributes[:password]
	end

	def authenticate!
		user = User.authenticate(@email, @password)

		if user.present?
			store(user)
		else
			errors.add(:base, :invalid_login)
			false
		end
	end

	def store(user)
		@session[:user_id] = user.id
	end

	def current_user
		User.find(@session[:user_id])
	end

	def user_signed_in?
		@session[:user_id].present?
	end

	def destroy
		@session[:user_id] = nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  delegate :current_user, :user_signed_in?, to: :user_session
  helper_method :current_user, :user_signed_in?
  protect_from_forgery with: :exception

  before_action do
  	I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
  	{ locale: I18n.locale }
  end

  def user_session
  	UserSession.new(session)
  end

  def require_authentication
  	unless user_signed_in?
  		redirect_to new_user_sessions_path, alert: t('flash.alert.needs_login')
  	end
  end

  def require_no_authentication
  	if user_signed_in?
  		redirect_to rooth_path, notice: t('flash.notice.already_logged_in')
  	end
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
	def show
		user = User.find_by(codigo_confirmacao: params[:token])

		if user.present?
			user.confirm!
			redirect_to user, notice: I18n.t('confirmations.success')
		else
			redirect_to root_path
		end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@rooms = Room.take(3)
	end
end

app/controllers/rooms/reviews_controller.rb
class Rooms::ReviewsController < ApplicationController
	before_filter :require_authentication

	def create
		review = room.reviews.
		  find_or_initialize_by(user_id: current_user.id)

		review.update!(review_params)

		head :ok
	end

	def update
		create
	end

	private

	def room
		@room ||= Room.find(params[:room_id])
	end

	def review_params
		params.
		  require(:review).permit(:points)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show]
  before_action :set_users_room, only: [:edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]

  def index
    @rooms = Room.most_recent.map do |room|
      RoomPresenter.new(room, self, false)
    end
  end

  def show
    if user_signed_in?
      @user_review = @room.reviews.
        find_or_initialize_by(user_id: current_user.id)
    end
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

      if @room.save
        redirect_to @room, notice: t('flash.notice.room_created')
      else
        render :new
      end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update

      if @room.update(room_params)
        redirect_to @room, notice: t('flash.notice.room_updated')
      else
        render :edit
      end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
      redirect_to rooms_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      room_model = Room.find(params[:id])
      @room = RoomPresenter.new(room_model, self)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end

    def set_users_room
      @room = current_user.rooms.find(params[:id])

    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	before_action :require_no_authentication, only: [:new, :create]
	before_action :require_authentication, only: :destroy
	
	def new
		@user_session = UserSession.new(session)
	end

	def create
		@user_session = UserSession.new(session, params[:user_session])

		if @user_session.authenticate!
			redirect_to root_path, notice: t('flash.notice.signed_in')
		else
			render :new
		end
	end

	def destroy
		user_session.destroy
		redirect_to root_path, notice: t('flash.notice.signed_out')
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_no_authentication, only: [:new, :create]
	before_action :can_change, only: [:edi, :update]
	def show
		@user = User.find(params[:id])
		
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			Signup.confirm_email(@user).deliver
			redirect_to @user, notice: 'Cadastrado com Sucesso!'
		else
			render action: :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user,
				notice: 'Cadastro atualizado com Sucesso!'
		else
			render action: :edit
		end
	end

	private

	def user_params
		params.
			require(:user).
			permit(:email, :full_name, :location, :password, :password_confirmation, :bio)
	end

	def can_change
		unless user_signed_in? && current_user == user
			redirect_to user_path(params[:id])
		end
	end

	def user
		@user ||= User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def error_tag(model, attribute)
		if model.errors.has_key? attribute
			content_tag(
				:div,
				model.errors[attribute].first,
				class: 'error_message'
			)
		end
	end
end

app/helpers/confirmations_controller_helper.rb
module ConfirmationsControllerHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
	def belongs_to_user(room)
		user_signed_in? && room.user == current_user
	end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/home/index.html.erb
<h1>Quartos récem postados</h1>
<ul>
	<% @rooms.each do |room| %>
		<li>
			<%= link_to room.complete_name, room%>
		</li>
	<% end %>
</ul>

app/views/layouts/_user_navbar.html.erb
<nav>
	<ul>
		<li><%= link_to t('layout.new_room'), new_room_path %></li>
		<li><%= link_to t('layout.rooms'), rooms_path %></li>
		<li>
			<%= link_to t('layout.my_profile'), user_path(current_user) %>
		</li>
		<li>
			<%= link_to t('layout.signout'), user_sessions_path, method: :delete %>
		</li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Pacifico">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div id="header-wrap">
			<h1><%= link_to "colcho.net", root_path %></h1>
			<% if user_signed_in? %>
				<%= render 'layouts/user_navbar' %>
			<% else %>
				<%= render 'layouts/visitor_navbar' %>
			<% end %>
		</div>
	</header>

	<div id="content">
		<% if notice.present? %>
			<p id="notice"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
			<p id="alert"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_review.html.erb
<section class="review">
  <% if room.show_form? %>
    <%= render partial: 'review_form', locals: {room: room} %>
  <% else %>
    <% room.stars.times do %>
      <%= fa_icon 'star' %>
    <% end %>
    <%(room.review_points.max - room.stars).times do %>
      <%= fa_icon 'empty-star' %>
      <% end %>
    <%= t '.stats', count: room.total_reviews %>
  <% end %>
</section>

app/views/rooms/_review_form.html.erb
<% if room.can_review? %>
  <%= form_for room.review_route, remote: true do |f| %>
    <% room.review_points.each do |point| %>
      <%= f.radio_button :points, point %>
      <%= f.label :points, value: point do%>
        <%= fa_icon 'star' %>
        <% end %>
    <% end %>

    <%= f.submit %>
  <% end %>
<% else %>
<span class="login_required">
  <%= t('.login_to_review') %>
</span>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
    <h2><%= link_to room.title, room.route %></h2>

    <%= render partial: 'review', locals: {room: room} %>

    <span class="created">
      <%= t '.owner_html', owner: room.user.full_name, when: l(room.created_at, format: :short) %>
    </span>
    <p>
      <span class="location">
        <%= link_to room.location, "https://maps.google.com/?q=#{room.location}", target: :blank %>
      </span>
    </p>
    <p><%= room.description %></p>
    <% if belongs_to_user(room) %>
      <ul>
        <li><%= link_to t('.edit'), edit_room_path(room.route) %></li>
        <li><%= link_to t('.destroy'), room_path(room.route), method: :delete, data: {confirm: t('dialogs.destroy')}%></li>
      </ul>
    <% end %>
  </article>

app/views/rooms/edit.html.erb
<h1><%= t 'layout.editing_room' %></h1>

<%= render 'form' %>

<%= link_to t('links.show'), @room %> |
<%= link_to t('links.back'), rooms_path %>

app/views/rooms/index.html.erb
<h1><%= t '.title' %></h1>

<%= render @rooms %>

app/views/rooms/new.html.erb
<h1><%= t 'layout.new_room' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/signup/confirm_email.html.erb
<h1><%= t '.title' %></h1>
<p>
	<%= t '.body', full_name: @user.full_name %>
</p>
<p>
	<%= t '.confirm_link_html',
		link: link_to(@confirmation_link, @confirmation_link) %>
</p>
<p>
	<%= t '.thanks_html', link: link_to('Colcho.net', root_url) %>
</p>

app/views/signup/confirm_email.text.erb
<%= t '.body', full_name: @user.full_name %>
<%= t '.confirm_link_html', link: @confirmation_link %>

<%= t '.thanks_html', link: root_url %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title'%></h1>

<% if @user_session.errors.has_key? :base %>
	<div id="error_explanation">
		<%= @user_session.errors[:base].join(', ') %>
	</div>
<% end %>

<%= form_for @user_session do |f| %>
	<p>
		<%= f.label :email %> <br>
		<%= f.text_field :email %> <br>
		<%= error_tag @user_session, :email %>
	</p>
	<p>
		<%= f.label :password %> <br>
		<%= f.password_field :password %> <br>
		<%= error_tag @user_session, :password %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %></p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<%= t 'general.form_error'%>
	</div>
<% end %>

<%= form_for @user do |f| %>
	<p>
		<%= f.label :full_name %> <br/>
		<%= f.text_field :full_name %>
		<%= error_tag @user, :full_name %>
	<p>
	<p>
		<%= f.label :location %> <br/>
		<%= f.text_field :location %>
		<%= error_tag @user, :location %>
	</p>
	<p>
		<%= f.label :email %> <br/>
		<%= f.text_field :email %>
		<%= error_tag @user, :email %>
	</p>
	<p>
		<%= f.label :password %> <br/>
		<%= f.password_field :password %>
		<%= error_tag @user, :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %> <br/>
		<%= f.password_field :password_confirmation %>
		<%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.label :bio %><br/>
		<%= f.text_area :bio %>
		<%= error_tag @user, :bio %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1> <%= t 'users.new.title' %></h1>

<%= render 'form' %>

<%= link_to "Voltar", root_path %>

app/views/users/show.html.erb
<h1><%= t '.title', user_name: @user.full_name %></h1>

<ul>
	<li><%= t '.location', location: @user.location %></li>
	<li><%= t '.bio', bio: @user.bio %></li>
</ul>

<%= link_to t('.edit'), edit_user_path(@user) %>